2018-12-18 20:17:13,143 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:17:17,142 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:17:17,142 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:43:00,252 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:43:04,382 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:43:04,382 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:46:01,227 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:46:02,980 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:46:02,980 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:51:20,259 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:51:21,968 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:51:21,968 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:53:53,621 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:53:57,149 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 20:53:57,149 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:29:02,659 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:29:06,780 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:29:06,780 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:32:38,718 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:32:43,995 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:32:43,995 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:39:12,345 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:39:14,114 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:39:14,114 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:48:18,759 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:48:20,526 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:48:20,526 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:51:18,426 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:51:21,706 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:51:21,706 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:53:01,089 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:53:06,736 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:53:06,736 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:55:43,854 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:55:48,074 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 21:55:48,074 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:03:29,201 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:03:30,971 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:03:30,971 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:21:05,216 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:21:07,948 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:21:07,948 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:22:10,747 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:22:13,501 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:22:13,501 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:24:42,224 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:24:45,392 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:24:45,392 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:28:14,911 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:28:16,648 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:28:16,648 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:29:47,133 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:29:52,541 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:29:52,541 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:31:37,522 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:31:41,344 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:31:41,344 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:37:32,873 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:37:35,046 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:37:35,046 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:42:51,637 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:42:53,895 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:42:53,895 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:43:17,377 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:43:20,241 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:43:20,241 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:47:28,206 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:47:31,134 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:47:31,134 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:52:59,407 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:53:02,185 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:53:02,185 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:54:41,989 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:54:46,066 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:54:46,066 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:59:24,086 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:59:26,427 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 22:59:26,427 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:21:27,111 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:21:30,713 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:21:30,713 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:26:36,961 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:26:39,770 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:26:39,770 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:28:48,293 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:28:51,749 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:28:51,749 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:29:31,472 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:29:35,031 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:29:35,031 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:30:13,182 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:30:15,986 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:30:15,986 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:31:42,970 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:31:45,263 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:31:45,263 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:32:43,237 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:32:46,523 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:32:46,523 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:34:09,608 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:34:13,192 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:34:13,192 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:39:32,091 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:39:34,811 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-18 23:39:34,811 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 08:31:07,729 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 08:31:11,769 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 08:31:11,769 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 09:20:30,567 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 09:20:38,721 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 09:20:38,721 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 09:20:56,975 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 09:20:56,975 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 09:20:56,979 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 09:20:56,979 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 10:24:07,761 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:24:10,704 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:24:10,704 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:50:59,545 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:51:17,173 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:51:17,173 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:55:07,239 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:55:17,309 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:55:17,309 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 10:57:04,110 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 10:57:04,110 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 10:57:04,113 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 10:57:04,113 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 12:46:14,040 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 12:46:20,971 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 12:46:20,971 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:01:51,223 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:01:56,698 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:01:56,698 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:04:21,041 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 13:04:21,041 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 13:04:21,050 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 13:04:21,050 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 13:07:26,000 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:07:30,849 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:07:30,849 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:09:41,556 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 13:09:41,556 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 13:09:41,558 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 13:09:41,558 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 13:13:51,857 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:13:55,703 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:13:55,703 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:31:48,603 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:31:50,666 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:31:50,666 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:35:34,365 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:35:36,537 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:35:36,537 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:44:14,531 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:44:17,156 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 13:44:17,156 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:08:59,315 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:09:02,438 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:09:02,438 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:28:06,324 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:28:17,257 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:28:17,257 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:42:36,973 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:42:40,135 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:42:40,135 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:47:30,190 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:47:33,879 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:47:33,879 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:56:43,846 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:56:47,123 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:56:47,123 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 14:59:17,449 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 14:59:17,449 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 14:59:17,451 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 14:59:17,451 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 15:16:57,608 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:17:07,437 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:17:07,437 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:18:28,621 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:18:32,279 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:18:32,279 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:23:44,231 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:23:47,521 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:23:47,521 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:26:52,752 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 15:26:52,752 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 15:26:52,753 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 15:26:52,753 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 15:27:34,898 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:27:38,513 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:27:38,513 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:32:09,428 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:32:13,216 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:32:13,216 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:34:04,537 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:34:08,321 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:34:08,321 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:49:57,956 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:50:00,010 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:50:00,010 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:57:19,890 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:57:22,006 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:57:22,006 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:58:49,684 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:58:54,396 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 15:58:54,396 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 16:18:53,496 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 16:18:55,581 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 16:18:55,581 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:19:37,303 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:19:40,714 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:19:40,714 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:28:25,553 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:28:27,754 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:28:27,754 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:30:22,449 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 17:30:22,449 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 17:30:22,451 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 17:30:22,451 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 17:40:19,452 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:40:22,644 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:40:22,644 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:42:09,078 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:42:13,671 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:42:13,671 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:44:09,370 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:44:14,172 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:44:14,172 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:44:48,420 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 17:44:48,420 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 17:44:48,424 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 17:44:48,424 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 17:48:27,365 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:48:32,706 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:48:32,706 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:49:24,314 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:49:28,374 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 17:49:28,374 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 19:59:14,150 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 19:59:20,737 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 19:59:20,737 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:01:05,895 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:01:15,924 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:01:15,924 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:03:59,740 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:04:15,882 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:04:15,882 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:05:48,384 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 20:05:48,384 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 20:05:48,396 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 20:05:48,396 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 20:07:26,345 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 20:07:26,345 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 20:07:26,349 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 20:07:26,349 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 20:16:45,195 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:16:55,936 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:16:55,936 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:20:14,728 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:20:19,707 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:20:19,707 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:23:48,316 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:23:52,263 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:23:52,263 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:26:22,620 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:26:26,208 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:26:26,208 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:31:41,074 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:31:44,475 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:31:44,475 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 20:33:54,983 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 20:33:54,983 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 20:33:54,985 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 20:33:54,985 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 21:39:32,099 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:39:34,668 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:39:34,668 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:42:12,335 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:42:15,453 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:42:15,453 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:48:24,147 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:48:26,135 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 21:48:26,135 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:24:55,400 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:24:59,944 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:24:59,944 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:26:46,078 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:26:52,198 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:26:52,198 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:31:01,512 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 22:31:01,512 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 22:31:01,516 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 22:31:01,516 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 22:32:44,209 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:32:49,137 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:32:49,137 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:36:22,489 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:36:27,441 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:36:27,441 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:39:12,650 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 22:39:12,650 - logs/hashrate.logs:87 - ERROR - plot error:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 83, in difficulty_plot
    p = df.hvplot.line(x='block_number',y='difficulty',
AttributeError: 'NoneType' object has no attribute 'hvplot'
2018-12-19 22:39:12,655 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 22:39:12,655 - logs/hashrate.logs:133 - ERROR - rendering err:
Traceback (most recent call last):
  File "/home/andre/aion/data_science/bokeh/aion_analytics/scripts/dashboards/streaming/hashrate.py", line 108, in hashrate_tab
    dmap_diff = hv.DynamicMap(difficulty_plot(),datashade=True)\
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 760, in __init__
    if self.callback.noargs:
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 525, in noargs
    return self.argspec == noargs
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/spaces.py", line 519, in argspec
    return util.argspec(self.callable)
  File "/home/andre/anaconda3/envs/bokeh_aion_analytics/lib/python3.5/site-packages/holoviews/core/util.py", line 273, in argspec
    return argspec(callable_obj.__call__)
AttributeError: 'NoneType' object has no attribute '__call__'
2018-12-19 22:39:20,088 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:39:23,134 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
2018-12-19 22:39:23,134 - logs/hashrate.logs:15 - WARNING - logs/hashrate.logs
